"""Python reference implementation of the Binsparse specification."""

from .container import (
    BINSPARSE_HEADER,
    BinsparseContainer,
    HDF5BinsparseContainer,
    InMemoryBinsparseContainer,
    NPZBinsparseContainer,
    ZarrBinsparseContainer,
)
from .errors import BinsparseParseError
from .io import load_binsparse, save_binsparse
from .tensor import (
    BinsparseLevel,
    BinsparseTensor,
    COOCMatrix,
    COOMatrix,
    COORMatrix,
    CSCMatrix,
    CSRMatrix,
    CustomTensor,
    DCSCMatrix,
    DCSRMatrix,
    DMATCMatrix,
    DMATMatrix,
    DMATRMatrix,
    DVECVector,
    CVECVector,
    DenseLevel,
    ElementLevel,
    IndexableLevel,
    SparseLevel,
)
from .version import BINSPARSE_VERSION

__all__ = [
    "BINSPARSE_HEADER",
    "BINSPARSE_VERSION",
    "BinsparseContainer",
    "BinsparseLevel",
    "BinsparseParseError",
    "BinsparseTensor",
    "COOCMatrix",
    "COOMatrix",
    "COORMatrix",
    "CSCMatrix",
    "CSRMatrix",
    "CVECVector",
    "CustomTensor",
    "DCSCMatrix",
    "DCSRMatrix",
    "DMATCMatrix",
    "DMATMatrix",
    "DMATRMatrix",
    "DVECVector",
    "DenseLevel",
    "ElementLevel",
    "HDF5BinsparseContainer",
    "InMemoryBinsparseContainer",
    "IndexableLevel",
    "load_binsparse",
    "NPZBinsparseContainer",
    "SparseLevel",
    "save_binsparse",
    "ZarrBinsparseContainer",
]
